name: Сборка Demo

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build demo
    runs-on: ubuntu-latest

    steps:
      - name: Извлечение исходников
        uses: actions/checkout@v4

      - name: Установка NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'yarn.lock'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile

      - name: Сборка сайта с документацией
        run: yarn build-playground

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist/'

  # Deploy job
  deploy:
    name: Deploy demo
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4